FROM python:3.12-slim
WORKDIR /admin
COPY django_admin/requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt || true
COPY django_admin/ ./
CMD ["python", "manage.py", "runserver", "0.0.0.0:8001"]
